#!/bin/bash

# Load environment variables from .env file
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
else
  echo ".env file not found!"
  exit 1
fi

# Step 1: Pull the specified Docker image for linux/amd64 platform
docker pull --platform linux/amd64 etherspot/skandha:v4-latest

# Step 2: Tag the pulled image with the new name
docker tag etherspot/skandha:v4-latest zircuit-garfield-mainnet:latest

# Step 3: Run the container with the required environment variables and options
docker run --platform linux/amd64 --pull=never -d \
  --name zircuit-garfield-mainnet \
  -p 14337:14337 \
  -e SKANDHA_EIP7702="true" \
  -e SKANDHA_GAS_FEE_IN_SIMULATION="true" \
  -e SKANDHA_POLLING_INTERVAL="15000000" \
  -e SKANDHA_BUNDLE_INTERVAL="2000" \
  -e SKANDHA_PRECOMPILES="0x0000000000000000000000000000000000000001" \
  -e SKANDHA_DISABLE_WATCH_CONTRACT="false" \
  -e SKANDHA_VGL_MARKUP_PERCENT="4000" \
  -e SKANDHA_CGL_MARKUP_PERCENT="2000" \
  -e SKANDHA_PVG_MARKUP_PERCENT="3000" \
  -e SKANDHA_PIMLICO_SIMULATIONS_CONTRACT="0x7BA8C88100E80F90b6825A1F1E106d96bEb5B1C6" \
  -e SKANDHA_EP_SIMULATIONS_CONTRACT="0xC930a3631e2477Af713A328c49B56699904688C4" \
  -e SKANDHA_RELAYERS="$RELAYER_VALUE" \
  -e SKANDHA_RPC="https://mainnet.zircuit.com" \
  -e SKANDHA_ENTRYPOINTS="0x433709009B8330FDa32311DF1C2AFA402eD8D009" \
  zircuit-garfield-mainnet:latest \
  standalone \
  --redirectRpc \
  --metrics.enable \
  --metrics.host=0.0.0.0
